import Head from 'next/head'
import { Button } from '@mantine/core';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Flows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Click me!</Button>
    </div>
  )
}
